// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtG9_tmVkLlJ4dxVYsBheDe4gDact0g9I',
    appId: '1:110242009728:web:664772ced3d7d87bf94c65',
    messagingSenderId: '110242009728',
    projectId: 'lapor-book-b7725',
    authDomain: 'lapor-book-b7725.firebaseapp.com',
    storageBucket: 'lapor-book-b7725.appspot.com',
    measurementId: 'G-M0HCMKZ8N8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1UAfNxEByhSBx3zCGN2jLly1mPhTyJzU',
    appId: '1:110242009728:android:9938dafb98999fe4f94c65',
    messagingSenderId: '110242009728',
    projectId: 'lapor-book-b7725',
    storageBucket: 'lapor-book-b7725.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEou3XdpOq5Qhi86oaDuufexJ2L2Nly24',
    appId: '1:110242009728:ios:2085aa0839b590f4f94c65',
    messagingSenderId: '110242009728',
    projectId: 'lapor-book-b7725',
    storageBucket: 'lapor-book-b7725.appspot.com',
    iosBundleId: 'com.example.laporBook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEou3XdpOq5Qhi86oaDuufexJ2L2Nly24',
    appId: '1:110242009728:ios:2085aa0839b590f4f94c65',
    messagingSenderId: '110242009728',
    projectId: 'lapor-book-b7725',
    storageBucket: 'lapor-book-b7725.appspot.com',
    iosBundleId: 'com.example.laporBook',
  );
}
